name: Doctest

on:
  push:
    paths-ignore:
      - 'notebooks/**'

jobs:
  test-doctest-module:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        python -m pip install tox-pip-extensions

    - name: Run Doctests
      run: |
        make tests-doctest-modules
